### PR TITLE
fix(various): Typo in loan, refactor crypto -> digital

### LINKED ISSUE #34: src/finance/loan.cto
There's a typo in the properties of the concept Loan, lein should be lien.

### PR DESCRIPTION
**Pull request by mttrbrts**
Updates to various models in accordance with the new versioning scheme (#15).

- `time@0.2.0` is a re-release of `v2/time.cto` to bring it into line with the new versioning scheme.
- `money@0.2.0` uses `DigitalMonetaryAmount` rather than `CrytoMonetaryAmount`
- `loan@0.2.0.cto` is fixed to address a typo. Fixes #34 .
- All models now use `time@0.2.0` and `money@0.2.0`

### CODE REVIEW

**Comment by mttrbrts** [comment]
> Have we tested import in Cicero with this naming scheme?

Yes, I just tried this with latedeliveryandpenalty, all looks good. `cicero parse` downloaded and cached the time model properly.
image

**Comment by jeromesimeon** [comment]
> > How do those appear on the published model library page?
> 
> I'm glad that you asked, it seems that I missed this file altogether!
> https://5d08f534bd97ad00090c6522--accordproject-models.netlify.com/time@0.2.0.html

Screenshot 2019-06-18 at 10 56 20 AM

It would be nice if we could identify the latest version more easily.

Also, it doesn't seem to pick up all the versions? (I see only one loan?)

**Comment by mttrbrts** [comment]
> It would be nice if we could identify the latest version more easily.

I'll make a small change to the show the full name in the library list for now. Eventually, these can be collapsed like on the templates pages.

> Also, it doesn't seem to pick up all the versions? (I see only one loan?)

This is because the new loan model has a dependency on a model that doesn't yet exist. Perhaps I should have released each of these changes separately? That's not ideal if the changes really are related.

**Comment by jeromesimeon** [comment]
> > It would be nice if we could identify the latest version more easily.
> 
> I'll make a small change to the show the full name in the library list for now. Eventually, these can be collapsed like on the templates pages.
> 
> > Also, it doesn't seem to pick up all the versions? (I see only one loan?)
> 
> This is because the new loan model has a dependency on a model that doesn't yet exist. Perhaps I should have released each of these changes separately? That's not ideal if the changes really are related.

That's a little bit confusing, but maybe we can fix those after the PR has been merged? The `build.js` script should probably be fixed.

**Comment by mttrbrts** [comment]
I've made a change to the build script to add the version parsed from the filename.
image

Parsing the filename to extract the version string is pretty straightforward:
```
filename.split("@").pop().slice(0,-4);
```

**Pull request merged**
