### PR TITLE
Design updates 2019 6

### PR DESCRIPTION
**Pull request by javiercanossini**

### CODE REVIEW

**Comment by mttrbrts** [comment]
@javiercanossini Can you resolve the conflicts, please?
@Michael-Grover, ok?

**Comment by Michael-Grover** [comment]
@mttrbrts @javiercanossini this looks good to me

**Comment by Michael-Grover** [comment]
@javiercanossini @mttrbrts actually it looks like the proportions of our logo are stretched here and in the template library
image

**Comment by Michael-Grover** [comment]
@javiercanossini thanks, this looks good. Can you apply this fix to the template library too?

**Comment by Michael-Grover** [comment]
@javiercanossini I just saw your note that both are updated. @mttrbrts the PRs on this and the template library are good to go.

**Pull request merged**
