### PR TITLE
Peer review for org.accordproject.finance.loan

### PR DESCRIPTION
**Pull request by bucs-fan813**
I am new to accord and hyperledger. I am considering building an app for loans that uses accord and cicero based technology. Please review and let me know what changes should be added. Thanks

### CODE REVIEW

**Comment by mttrbrts** [comment]
Welcome @bucs-fan813 ! Thanks for your contribution. 

I suggest refactoring so that this file contains just the loan model. The Contract and Clause models would fit better within a Cicero template IMO https://github.com/accordproject/cicero-template-library/

It is feasible (and encouraged!) that your model could be used in a non-Cicero context too, for example within HL Composer or HL Fabric project.

**Comment by mttrbrts** [comment]
Welcome @bucs-fan813 ! Thanks for your contribution. 

I suggest refactoring so that this file contains just the loan model. The Contract and Clause models would fit better within a Cicero template IMO https://github.com/accordproject/cicero-template-library/

It is feasible (and encouraged!) that your model could be used in a non-Cicero context too, for example within HL Composer or HL Fabric project.

**Comment by mttrbrts** [comment]
Welcome @bucs-fan813 ! Thanks for your contribution. 

I suggest refactoring so that this file contains just the loan model. The Contract and Clause models would fit better within a Cicero template IMO https://github.com/accordproject/cicero-template-library/

It is feasible (and encouraged!) that your model could be used in a non-Cicero context too, for example within HL Composer or HL Fabric project.

**Comment by mttrbrts** [comment]
Welcome @bucs-fan813 ! Thanks for your contribution. 

I suggest refactoring so that this file contains just the loan model. The Contract and Clause models would fit better within a Cicero template IMO https://github.com/accordproject/cicero-template-library/

It is feasible (and encouraged!) that your model could be used in a non-Cicero context too, for example within HL Composer or HL Fabric project.

**Comment by mttrbrts** [comment]
Welcome @bucs-fan813 ! Thanks for your contribution. 

I suggest refactoring so that this file contains just the loan model. The Contract and Clause models would fit better within a Cicero template IMO https://github.com/accordproject/cicero-template-library/

It is feasible (and encouraged!) that your model could be used in a non-Cicero context too, for example within HL Composer or HL Fabric project.

**Comment by mttrbrts** [comment]
Welcome @bucs-fan813 ! Thanks for your contribution. 

I suggest refactoring so that this file contains just the loan model. The Contract and Clause models would fit better within a Cicero template IMO https://github.com/accordproject/cicero-template-library/

It is feasible (and encouraged!) that your model could be used in a non-Cicero context too, for example within HL Composer or HL Fabric project.

**Comment by mttrbrts** [comment]
Welcome @bucs-fan813 ! Thanks for your contribution. 

I suggest refactoring so that this file contains just the loan model. The Contract and Clause models would fit better within a Cicero template IMO https://github.com/accordproject/cicero-template-library/

It is feasible (and encouraged!) that your model could be used in a non-Cicero context too, for example within HL Composer or HL Fabric project.

**Comment by mttrbrts** [comment]
Apologies for duplicate comments. Issues with GH this morning.

**Comment by bucs-fan813** [comment]
No worries. I have revised to contain just the loan model. That is my intent to make this compatible with HL Composer. This is my first try at DLT development. Apologies in advance if I am completely lost on some of the core concepts. 

Regarding the cicero contract and clauses, it seems like that should be drafted or reviewed by a lawyer rather than a developer. Do lawyers do that here or is there a more appropriate forum for contract review?

**Comment by mttrbrts** [comment]
The Accord Project (http://accordproject.org/) working groups are a great place for exactly this kind of legal / tech collaboration, you're very welcome to join us via slack.

**Pull request closed without merging**
