### PR TITLE
feat(views): utilize AP logo - I80

### PR DESCRIPTION
**Pull request by CoryWritesCode**
# Issue #80 
Swapped the old logo and title for the new one.

### Changes
Just had the img for the logo that was in place use the same design as the other `models` page for the header. Removed the `span` because the new logo has the brand label in it.

### CODE REVIEW

**Comment by CoryWritesCode** [comment]
Just added @irmerk :)

**Comment by irmerk** [comment]
@mttrbrts unsure where the Netlify of this is.

**Comment by irmerk** [comment]
I believe you'll need to add this picture to the models repository: https://github.com/accordproject/techdocs/blob/master/website/static/img/A-MARK-ACCORDPROJECT-ONELINE-white.svg

**Comment by CoryWritesCode** [comment]
Yeah, sorry, with not being able to serve locally I'm having a hard time testing the changes.

**Comment by irmerk** [comment]
I'm not as familiar with nunjucks, so unsure if there's a straightforward way to serve locally. Otherwise just reference https://deploy-preview-81--accordproject-models.netlify.com/ when you force push back up.

**Comment by CoryWritesCode** [comment]
@irmerk working now. Sorry for all the troubleshooting.

**Comment by jeromesimeon** [comment]
This looks huge:
Screenshot 2019-10-28 at 9 25 12 PM

**Comment by CoryWritesCode** [comment]
Looks normal on mine (chrome). What browser are you using?
image

**Comment by jeromesimeon** [comment]
> Looks normal on mine (chrome). What browser are you using?
> image

I was trying with Safari. Chrome does look fine on my machine too (MacOS).

The logo is completely missing on Firefox:
Screenshot 2019-10-29 at 9 24 32 AM

**Comment by irmerk** [comment]
Unsure why it's still larger than it should be

Your PR:
Screen Shot 2019-10-29 at 10 09 56 AM

Current docs.accordproject.org:
Screen Shot 2019-10-29 at 10 09 46 AM

**Comment by CoryWritesCode** [comment]
Because there's no version number. I can lower it still if you want.

**Comment by irmerk** [comment]
> Because there's no version number. I can lower it still if you want.

Ah that would make sense. @jeromesimeon @peterhunn @Michael-Grover ?

https://deploy-preview-81--accordproject-models.netlify.com/
https://docs.accordproject.org/

**Comment by CoryWritesCode** [comment]
@irmerk What do you think of latest?

**Comment by irmerk** [comment]
This looks fine on Chrome, but is not rendering on Firefox and looks huge on Safari. I think we need to look into what the issue is here, maybe that it's an `svg`? @Michael-Grover?

**Comment by irmerk** [comment]
> the docs page is using an svg as well. I bet it's the way the header/navbar is implemented. They are completely different on both pages.

That would make sense. Could take some tinkering with the `css`, since the `img` has a `class="logo"`

**Comment by CoryWritesCode** [comment]
Got it. 
Pushing up the fix now.
Screen Shot 2019-10-30 at 10 37 25 AM

**Comment by irmerk** [comment]
I'm still seeing it too big on Safari and nonexistent on Firefox.

**Comment by CoryWritesCode** [comment]
ugh it didn't push the change

**Comment by irmerk** [comment]
Thanks for all the work @CoryWritesCode! 

Not seeing the Netlify build in the checks now, weird. I'll check in again after lunch.

**Pull request merged**
