### PR TITLE
add language model

### PR DESCRIPTION
**Pull request by peterhunn**
Model for defining governing/translated language in contracts

Signed-off-by: Peter Hunn <code@peterhunn.com>

### CODE REVIEW

**Comment by jeromesimeon** [comment]
Very nice! Is there a source for that list? (how do we know we did not miss anything?).

**Comment by peterhunn** [comment]
> Very nice! Is there a source for that list? (how do we know we did not miss anything?).

Taken from: https://www.searchify.ca/list-of-languages-world/. Suggestions for a more authoritative list very welcome.

**Comment by mttrbrts** [comment]
We should use a list based on a standard. Something like this, https://datahub.io/core/language-codes

**Comment by peterhunn** [comment]
Thanks @mttrbrts and @jeromesimeon. New PR using ISO standards: https://github.com/accordproject/models/pull/47

**Comment by dselman** [comment]
Superseded.

**Pull request closed without merging**
